### ISSUE TITLE
`nvim-treesitter.ts_utils.get_node_text` is deprecated

### ISSUE THREAD

**Issue by il-tmfv** [cuducos/yaml.nvim#11]
I started to get this message when yanking:
```
nvim-treesitter.ts_utils.get_node_text is deprecated: use vim.treesitter.query.get_node_text
```

```
$ nvim --version
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
```

`PlugSnapshot`:
```viml
silent! let g:plugs['nvim-treesitter'].commit = '09efcdb0498b60f698aa1e879e4ad07d84d1c1a5'
```

**Comment by cuducos** [comment]
Good caught. It looks like Neovim 0.7 is bringing in some code that used to live in nvim-treesitter. Although I could replace the method call as suggested in the error message, it looks like there's still something pending…

The treestiter module inside Neovim 0.7.0 tries to call `:start()` on a node, but it looks like we're not passing a node anymore, or a node does not have this method… not sure if _yet_ (they might still be porting these bits) or _anymore_ (API has changed).
```
E5108: Error executing lua ...im/0.7.0/share/nvim/runtime/lua/vim/treesitter/query.lua:185: attempt to call method 'start' (a nil value)                                                                      
stack traceback:
        ...im/0.7.0/share/nvim/runtime/lua/vim/treesitter/query.lua:185: in function 'get_node_text'
```

Anyway, gonna take a look one of these days with more time, but anyone is welcome to jump in with ideas and PRs : )
