### ISSUE TITLE
Error when running Yaml Telescope

### ISSUE THREAD

**Issue by erlingur** [cuducos/yaml.nvim#18]
```
E5108: Error executing lua ...im/site/pack/packer/opt/yaml.nvim/lua/yaml_nvim/init.lua:93: Vim(cexpr):E777: String or List expected
stack traceback:
        [C]: in function 'cmd'
        ...im/site/pack/packer/opt/yaml.nvim/lua/yaml_nvim/init.lua:93: in function 'telescope'
        [string ":lua"]:1: in main chunk
```

Any ideas? Running the latest version of Neovim and Telescope and yaml.nvim

**Comment by cuducos** [comment]
Thanks for reporting. I started to see that here today. Maybe something changed in `v:lua` — gonna take a look.

Any ideas (or PRs) are welcomed at this point : )

**Comment by erlingur** [comment]
That was fast! Thanks so much, this makes my day better :)

I tried to diagnose this but I'm terribly new to Lua and (n)vim plugins in general, sorry :)

**Comment by cuducos** [comment]
>  this makes my day better :)

Mine too (had a couple of 9k lines YAML to go through). Selfishlessness pushing open-source forward lol
