### ISSUE TITLE
Plugin not working with curly braces styles YAML block

### ISSUE THREAD

**Issue by jurij-robba** [cuducos/yaml.nvim#22]
~~From readme:~~

~~:YAMLTelescope	Full path key/value fuzzy finder via [Telescope](https://github.com/nvim-telescope/telescope.nvim) if installed~~

~~Currently the command opens quickfix instead.~~

**UPDATED** (by @cuducos) because it lacks precision. See following comments.

**Comment by cuducos** [comment]
What version of Neovim?

I cannot reproduce it. Can you follow these steps to make sure we have some isolation?

1. Create a temporary directory (I'll call it `/tmp/yaml-plugin-test`)
1. Copy our minimum [`init.lua`](https://github.com/cuducos/yaml.nvim/blob/main/tests/init.lua) to `/tmp/yaml-plugin-test/.config/nvim/init.lua`
1. Add `install("https://github.com/cuducos/yaml.nvim", "/tmp/yaml.nvim")` to `/tmp/yaml-plugin-test/.config/nvim/init.lua`
1. Add `install("https://github.com/nvim-telescope/telescope.nvim", "/tmp/telescope.nvim")` to `/tmp/yaml-plugin-test/.config/nvim/init.lua`
1. Set Neovim to temporarily use this `init.lua` instead, you can do that with `export XDG_CONFIG_HOME=/tmp/yaml-plugin-test/.config`

From there I opened `nvim some/file.yml` — I could `:YAMLTelescope` as expected.

**Comment by jurij-robba** [comment]
Sorry for late reply, easter and all.

NVIM 0.8.3 release with LuaJIT 2.1.0-beta3, running on majaro linux.

I went through the steps described in your prompt reply and i still get quickfix window, see screenshot attached.

![image](https://user-images.githubusercontent.com/30544241/230835115-91ff862b-adc4-4fce-a41a-0ea1b582db29.png)

I don't know any lua past what i learned trying to configure my nvim, but i had quick look at your code and this behaviour makes sense to me.

In your init.lua you have:
```lua
if has_telescope then
	vim.cmd("command! YAMLTelescope lua require('yaml_nvim').telescope()")
end
```

telescope function is defined as:

```lua
M.telescope = function()
	if not has_telescope then
		return
	end
	vim.cmd("cex v:lua.create_yaml_quickfix()")
	require("telescope.builtin").quickfix()
end
```

But again, i don't know lua so i might be completely misunderstanding things. but it would explain the behaviour i am seeing.

**Comment by cuducos** [comment]
Ok, so, good news: the screenshot you showed is quite the opposite: Telescope is opening and working! The window is a Telescope window showing the Quickfix results; that's how this plugin implements it.

I understand it's frustrating that no contents show up, but probably this is due to a YAML syntax error, not a plugin bug.

Is this YAML shareable (I mean, not proprietary or sensible)? If so, share it, or something similar, so I can check if that's really the case.

**Comment by jurij-robba** [comment]
Yes, telescope is indeed working, maybe i should specify that more explicitly from the get go. my problem is not that nothing happens. My problem is that quickfix shows up, when i expected to have searchable list of key value pairs, as described in the README (see initial issue).

**Comment by cuducos** [comment]
I got it. But you seem to have ignored the last part of my message. I need that to have how to try to reproduce it here. So, again:


> this is due to a YAML syntax error, not a plugin bug.
>
> Is this YAML shareable (I mean, not proprietary or sensible)? If so, share it, or something similar, so I can check if that's really the case.

**Comment by cuducos** [comment]
Ok. Got it. Thank you.
Indeed it seems to be a problem with the curly braces block.
Once I figure out how to run `TSInstall yaml` (see #21) on GitHub Action, I'll try to take a look.
