### ISSUE TITLE
Identation lines

### ISSUE THREAD

**Issue by ajsobrino96** [cuducos/yaml.nvim#24]
Maybe is not a bug and It is problem of my settings, but I am trying print the identation like the gif and I dont achieve. can you help me?

**Comment by cuducos** [comment]
Ow… this is why we all have to say thank you to @lukas-reineke — it's his amazing plugin [`indent-blankline.nvim`](https://github.com/lukas-reineke/indent-blankline.nvim) 💜

And it's not only for YAML, it's language-agnostic ✨ 

This is how I have it [installed](https://github.com/cuducos/dotfiles/blob/e27e2402e267fe8c5066f130283c2e6e21acfea9/.config/nvim/lua/plugins.lua#L189-L194) and [configured](https://github.com/cuducos/dotfiles/blob/main/.config/nvim/lua/config/indent.lua) in my own setup, if it helps 🚀
