### ISSUE TITLE
Using get_yaml_key with lualine destroys my color scheme

### ISSUE THREAD

**Issue by GDivino** [cuducos/yaml.nvim#27]
I'm currently loving yaml.nvim, but there's one thing that's kind of bugging me: When I use the get_yaml_key function with lualine, my whole color scheme changes and gets messed up. 

Ask: Has anyone experienced this? Any workarounds for this?

https://github.com/cuducos/yaml.nvim/assets/68019100/27241788-4766-4e2d-b51e-dacbcff8543f

**Comment by GDivino** [comment]
> yaml.nvim tweaks Neovim's filetype(see https://github.com/cuducos/yaml.nvim/issues/15), so can you check the filetype before and after calling get_yaml_key? :set ftmight do it ; )

Sorry about the video 😅. I was able to solve this thanks to `:set ft`. When the `get_yaml_key` function is used in lualine it changes the filetype to yaml for all the files. A workaround for this is to use autoCmd and reapply the lualine config whenever the buffer changes.

Will post the code in a bit ⏲️

**Comment by GDivino** [comment]
```lua
local yaml = require('yaml_nvim')
local GDivino_Lualine = vim.api.nvim_create_augroup("GDivino_Lualine", {})
local autocmd = vim.api.nvim_create_autocmd

function luaLineConf(content)
  require('lualine').setup({
    options = {
      icons_enabled = true,
      theme = 'auto',
      component_separators = { left = '', right = '' },
      section_separators = { left = '', right = '' },
      disabled_filetypes = {
        statusline = {},
        winbar = {},
      },
      ignore_focus = {},
      always_divide_middle = true,
      globalstatus = true,
      refresh = {
        statusline = 1000,
        tabline = 1000,
        winbar = 1000,
      }
    },
    sections = {
      lualine_a = { 'mode' },
      lualine_b = { 'branch', 'diff', 'diagnostics' },
      lualine_c = { 'filename' },
      lualine_x = { 'encoding', 'filetype' },
      lualine_y = { 'progress' },
      lualine_z = { 'location' }
    },
    tabline = {
      lualine_b = content,
    }
  })
end

autocmd({ 'BufWinEnter', 'FileType' }, {
  group = GDivino_Lualine,
  pattern = '*',
  callback = function()
    if vim.bo.ft ~= 'yaml' then
      luaLineConf({ 'filename' })
      return
    end

    luaLineConf({ yaml.get_yaml_key })
  end
})

```

**Comment by cuducos** [comment]
Really cleaver. Thank you. 

Inspired by your use case, I enhanced the `filetype` handling.
Now we just change the file type **if** the current one is a YAML-like 15c4cc1. I hope that helps.

I'll test that with different configs, but feel free to add more feedback to it : )
