### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by cuducos** [cuducos/yaml.nvim#3]
I have no experience in Lua, so I need a bit more of time to understand how I can write tests — any contribution (with code or references) are welcomed : )

**Comment by ellisonleao** [comment]
[plenary.nvim](https://github.com/nvim-lua/plenary.nvim/blob/master/TESTS_README.md) has some examples for creating tests inside neovim but it's not that straightforward unfortunately. For pure lua stuff, you definitely should use [busted](https://olivinelabs.com/busted/)
